services:
  server:
    build:
      context: ./server
    ports:
      - "9180:9180"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./data/db:/usr/src/app/.db
      - ./data/uploads:/usr/src/app/uploads
    restart: unless-stopped

  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    environment:
      NODE_ENV: production
    ports:
      - "7180:7180"